import request from 'supertest';
import app from '../../src/app';
import db from '../../src/db';

/**
 * FEATURE: Agent Profile & Branding (FEAT-102)
 * COVERAGE: API, Database, Validation, Security
 */

describe('FEAT-102: Agent Dashboard Profile Management API', () => {
  let agentToken: string;
  let buyerToken: string;
  let agentId: string;
  let userId: string;

  beforeAll(async () => {
    // Clear details
    await db.query('DELETE FROM agents');
    await db.query('DELETE FROM users');

    // Create Agent User
    const regRes = await request(app).post('/api/auth/register').send({
      email: 'marcus@vance.com',
      password: 'ComplexPass123!',
      fullName: 'Marcus Vance',
      role: 'agent',
      phone: '+12065550193',
      licenseNumber: 'RE-12345678'
    });
    userId = regRes.body.tokenReferenceId; // Placeholder lookup

    await db.query("UPDATE users SET is_verified = true WHERE email = 'marcus@vance.com'");
    const loginRes = await request(app).post('/api/auth/login').send({
      email: 'marcus@vance.com',
      password: 'ComplexPass123!'
    });
    agentToken = loginRes.body.token;

    // Retrieve agent ID generated by trigger/registration hooks
    const agentQuery = await db.query('SELECT id FROM agents WHERE user_id = $1', [loginRes.body.user.id]);
    agentId = agentQuery.rows[0].id;

    // Create Buyer
    await request(app).post('/api/auth/register').send({
      email: 'buyer@test.com',
      password: 'ComplexPass123!',
      fullName: 'Sarah Jenkins',
      role: 'buyer',
      phone: '+12065550000'
    });
    const buyerLogin = await request(app).post('/api/auth/login').send({
      email: 'buyer@test.com',
      password: 'ComplexPass123!'
    });
    buyerToken = buyerLogin.body.token;
  });

  afterAll(async () => {
    await db.close();
  });

  /**
   * TC-BE-102-01 (API & Database & Validation)
   * Requirement Mapping: FR-102-1, BRL-005
   * Priority: High
   */
  test('TC-BE-102-01: Update agent profile details validating social URL schemas', async () => {
    const payload = {
      bio: 'Premier commercial real estate specialist.',
      agencyName: 'Vance Group',
      facebook: 'https://facebook.com/marcus-vance',
      linkedin: 'https://linkedin.com/in/marcus-vance'
    };

    const res = await request(app)
      .put('/api/agents/profile')
      .set('Authorization', `Bearer ${agentToken}`)
      .send(payload)
      .expect(200);

    expect(res.body.status).toBe('success');

    // DB assertions
    const agentDb = await db.query('SELECT * FROM agents WHERE id = $1', [agentId]);
    expect(agentDb.rows[0].agency_name).toBe('Vance Group');
    expect(agentDb.rows[0].social_links.linkedin).toBe(payload.linkedin);
  });

  /**
   * TC-BE-102-02 (API & Validation & Negative)
   * Requirement Mapping: FR-102-1
   * Priority: High
   */
  test('TC-BE-102-02: Returns 400 validation error for invalid social domain URLs', async () => {
    await request(app)
      .put('/api/agents/profile')
      .set('Authorization', `Bearer ${agentToken}`)
      .send({
        bio: 'Invalid URLs test',
        linkedin: 'https://malicioussite.com/linkedin-clone' // Invalid domain check
      })
      .expect(400);
  });

  /**
   * TC-BE-102-03 (Security & Status Verification)
   * Requirement Mapping: US-102-1
   * Priority: High
   */
  test('TC-BE-102-03: Returns 404 block for public agent profile query if agent is suspended', async () => {
    // 1. Manually toggle agent status to suspended in user table
    await db.query("UPDATE users SET status = 'suspended' WHERE email = 'marcus@vance.com'");

    // 2. Query public profile from a buyer credentials perspective
    const res = await request(app)
      .get(`/api/agents/${agentId}`)
      .set('Authorization', `Bearer ${buyerToken}`)
      .expect(404);

    expect(res.body.code).toBe('PROFILE_UNAVAILABLE');

    // Restore user status for clean finish
    await db.query("UPDATE users SET status = 'active' WHERE email = 'marcus@vance.com'");
  });
});
