import request from 'supertest';
import app from '../../src/app'; // Mock Express Application Server Entry
import db from '../../src/db';   // Database pool connections

describe('FEAT-101: Workspace Setup & Invitations (Backend)', () => {
  let adminToken: string;
  let workspaceId: string;

  beforeAll(async () => {
    // Generate valid JWT session keys for mock Admin
    adminToken = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...';
    // Clear test DB tables
    await db.query('DELETE FROM workspace_invitation');
    await db.query('DELETE FROM user_workspace_role');
    await db.query('DELETE FROM workspace');
  });

  afterAll(async () => {
    await db.end();
  });

  /**
   * TC ID: TC-BE-101
   * Requirement Mapping: FR-101-2, FR-101-3
   * AC Mapping: AC-101-1, AC-101-2
   * Test Type: Functional / API / Database
   * Preconditions: DB connection active. User validated.
   * Steps:
   *   1. Issue POST `/api/v1/workspaces` payload `{"name": "Developer SandBox"}`.
   * Expected Result: Status returns 201. Database contains the workspace row and associates the user_id role as 'ADMIN'.
   * Priority: HIGH
   */
  test('TC-BE-101: Create Workspace & Verify Admin Role Allocation', async () => {
    const res = await request(app)
      .post('/api/v1/workspaces')
      .set('Authorization', adminToken)
      .send({ name: 'Developer SandBox' });

    expect(res.status).toBe(201);
    expect(res.body).toHaveProperty('workspace_id');
    workspaceId = res.body.workspace_id;

    // Database Write Verification
    const roleCheck = await db.query(
      'SELECT role FROM user_workspace_role WHERE workspace_id = $1',
      [workspaceId]
    );
    expect(roleCheck.rows[0].role).toBe('ADMIN');
  });

  /**
   * TC ID: TC-BE-102
   * Requirement Mapping: FR-101-5, FR-101-6
   * AC Mapping: AC-102-1, AC-102-2
   * Test Type: Functional / API / Database / Security
   * Preconditions: Workspace exists, sender holds ADMIN role.
   * Steps:
   *   1. Issue POST `/api/v1/workspaces/:workspace_id/invitations` containing `{"email": "editor@sandbox.com", "role": "EDITOR"}`.
   * Expected Result: Returns 200, inserts row in `workspace_invitation` table containing hashed/cryptographic token string, status is 'PENDING', and expires_at is set to current_time + 48 hours.
   * Priority: HIGH
   */
  test('TC-BE-102: Generate Cryptographic Invite Token and Store in DB', async () => {
    const res = await request(app)
      .post(`/api/v1/workspaces/${workspaceId}/invitations`)
      .set('Authorization', adminToken)
      .set('X-Workspace-ID', workspaceId)
      .send({ email: 'editor@sandbox.com', role: 'EDITOR' });

    expect(res.status).toBe(200);
    expect(res.body.status).toBe('PENDING');

    const dbInvite = await db.query(
      'SELECT token, expires_at FROM workspace_invitation WHERE email = $1',
      ['editor@sandbox.com']
    );
    expect(dbInvite.rows[0].token).toBeDefined();
    // Cryptographic entropy validation (checks for 64-char Hex token length)
    expect(dbInvite.rows[0].token.length).toBe(64);
  });

  /**
   * TC ID: TC-BE-103
   * Requirement Mapping: FR-101-5
   * AC Mapping: AC-102-1, AC-102-2
   * Test Type: Security / Negative / Workspace Isolation
   * Preconditions: Another user (Editor) attempts to send invitations.
   * Steps:
   *   1. Authenticate guest user as Editor role.
   *   2. Issue POST `/api/v1/workspaces/:workspace_id/invitations` targeting the workspace.
   * Expected Result: Status returns 403 Forbidden. Invitation table write is rejected.
   * Priority: CRITICAL
   */
  test('TC-BE-103: Block Team Invites Generated by Non-Admin Users', async () => {
    const editorToken = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9_EDITOR_MOCK...';
    const res = await request(app)
      .post(`/api/v1/workspaces/${workspaceId}/invitations`)
      .set('Authorization', editorToken)
      .set('X-Workspace-ID', workspaceId)
      .send({ email: 'another@sandbox.com', role: 'EDITOR' });

    expect(res.status).toBe(403);
    
    // DB verification that no row was written
    const checkRow = await db.query(
      'SELECT * FROM workspace_invitation WHERE email = $1',
      ['another@sandbox.com']
    );
    expect(checkRow.rows.length).toBe(0);
  });
});
